ci: clean up to pass linters #67
sassoftware/event-provenance-registry pull request #73
Opened 2024-01-12 21:35 UTC by xbcsmith

2024-01-12 23:05 UTC, caproven requested changes
I ran yamllint with the config from this PR against the main branch and didn't see errors for most of the changes made here, for instance
- wrapping *some* string in quotes
- favoring yaml lists (lines starting with `-`) instead of in-line arrays (`[a,b,c]`)

Can you share the exact linters you're running? I take it they're coming from your commit-hook repo.

I'm good with the changes except for one thing - I don't see a reason to remove empty lines from yaml files. It helps separate sections that can otherwise be hard to notice with indentation. Don't need to revert what you've done but I'd like to disable that rule if possible. Thoughts?

2024-01-12 23:05 UTC, caproven commented on docs/how-to/redpanda/multi-node/docker-compose.yaml
> -      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
The service is still named "redpanda-0", so updating addr flags here to "redpanda" break some networking (however the containers gracefully start). To reproduce, run `docker-compose up -d` in this dir and try hitting `http://localhost:8080`.

I'd suggest replacing any remaining instances of "redpanda-0" with just "redpanda". I tested this locally and could access the console UI as expected.

2024-01-12 23:08 UTC, xbcsmith commented
Linters https://github.com/xbcsmith/x-commit-hooks/blob/master/scripts/x-go-hooks.sh

2024-01-16 22:44 UTC, caproven approved these changes

2024-01-19 20:24 UTC, merged